services:
  - type: web
    name: doxbin
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app --bind 0.0.0.0:$PORT --workers 2
    autoDeploy: true
    envVars:
      PYTHON_VERSION: 3.12.3
